### ISSUE TITLE
Syntax error when running other commands

### ISSUE THREAD

**Issue by grappler** [wearerequired/wp-cli-clear-opcache#12]
When running any command I am getting the following error.

`Parse error: syntax error, unexpected ':', expecting ';' or '{' in /schtifti/staging/current/wordpress/wp-content/plugins/wp-cli-clear-opcache/inc/CLI_Command.php on line 18`

I have not had time to look into it further.

**Comment by swissspidy** [comment]
You‘re not using PHP7.1+, correct?

**Comment by grappler** [comment]
🤦‍♂️ Sorry, I remember this issue now. When testing this morning it seems to working now. Last night I did make a few changes so that the WP-CLI uses PHP7.1
